baseURL = 'https://jfiocchi.github.io'
languageCode = 'en-us'
title = 'J. Fiocchi'

# Hugo Modules
[module]
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5"

# Site parameters
[params]
  # Wowchemy theme
  theme = "minimal"
  day_night = true
  font = ""
  font_size = "l"
  
  # Contact info
  email = "your-email@domain.com"
  phone = "888 888 88 88"
  
  # Address
  address = {street = "450 Serra Mall", city = "Stanford", region = "CA", postcode = "94305", country = "United States", country_code = "US"}
  
  # Geographic coordinates
  coordinates = {latitude = "37.4275", longitude = "-122.1697"}
  
  # Directions for visitors to locate you.
  directions = "Enter Building 1 and take the stairs to Office 200 on Floor 2"
  
  # Office hours
  office_hours = ["Monday 10:00 to 13:00", "Wednesday 09:00 to 10:00"]
  
  # Enter an optional link for booking appointments (e.g. calendly.com).
  appointment_url = "https://calendly.com"
  
  # Contact links
  contact_links = [
    {icon = "twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/Twitter"},
    {icon = "github", icon_pack = "fab", name = "GitHub", link = "https://github.com/jfiocchi"},
    {icon = "envelope", icon_pack = "fas", name = "Email", link = "mailto:your-email@domain.com"}
  ]

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "#about"
    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "#posts"
    weight = 20

  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 30

  [[menu.main]]
    name = "Publications"
    url = "#featured"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 60

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
